# Generated by Django 5.0.1 on 2024-11-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_buyerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'buyerprofile', 'verbose_name_plural': 'buyerprofiles'},
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='password',
        ),
    ]
