# Generated by Django 5.0.1 on 2024-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='account_number',
            field=models.CharField(default='2041945260', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(default='2042060091', max_length=10),
        ),
    ]
