# Generated by Django 5.0.1 on 2024-11-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_buyerprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(default='2042606834', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='account_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
