# Generated by Django 5.0.1 on 2024-11-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_alter_customuser_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_number',
        ),
    ]
