# Generated by Django 5.0.1 on 2024-11-30 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_remove_customuser_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('15b7ba6e-c799-4a48-9caf-eeaef954f924')),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('vendor_identity', models.UUIDField(default='')),
                ('vendor_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_image1', models.ImageField(upload_to='image')),
                ('product_image2', models.ImageField(upload_to='image')),
                ('product_image3', models.ImageField(upload_to='image')),
                ('product_image4', models.ImageField(upload_to='image')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.vendorprofile')),
            ],
        ),
    ]
