# Generated by Django 5.0.1 on 2024-11-30 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_alter_product_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('bf6cb5c2-3c75-403d-ab7a-1adc4449e181')),
        ),
    ]
