# Generated by Django 5.0.1 on 2024-12-02 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_product_stock_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('3211e8fd-de09-497b-ac6c-500acf7cdda3')),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=500)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('vendor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('product_image', models.ImageField(null=True, upload_to='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
