# Generated by Django 5.0.1 on 2024-12-02 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_alter_vendorprofile_vendor_id_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_otp_token',
            field=models.CharField(default='be4c1622', max_length=8),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('43abf902-1c57-44fe-a793-5680e9b54f7b')),
        ),
    ]
