# Generated by Django 5.0.1 on 2024-12-02 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_orderdetail_delivered_orderdetail_order_otp_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('cda89c74-efbf-42de-98c8-cf7441c6bc41')),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_otp_token',
            field=models.CharField(default='8136163d', max_length=8),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('95799606-16bb-4c16-a22f-fb34007ce4c5')),
        ),
    ]
