# Generated by Django 5.0.1 on 2024-12-02 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('43b29908-3300-41a1-9926-4f0fae41a482')),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_otp_token',
            field=models.CharField(default='6a3b99ee', max_length=8),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('3483976e-704f-448f-a1f2-6a244b64cb61')),
        ),
    ]
