# Generated by Django 5.0.1 on 2024-12-02 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0021_alter_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('2198f052-73b2-4864-8f0a-e3aa0a9c3795')),
        ),
    ]
