# Generated by Django 5.0.1 on 2024-12-02 23:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_product_quantity_sold_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('0b305810-531f-461f-b83d-efa1d127ff61')),
        ),
    ]
