# Generated by Django 5.0.1 on 2024-12-05 21:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0024_product_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('f222b797-64b2-476c-a9bd-9f6bce71e8f1')),
        ),
    ]
