# Generated by Django 5.0.1 on 2024-12-12 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0025_product_uploaded_at_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('04100983-4d44-4449-b0a6-8db46ead6e3f')),
        ),
    ]
