# Generated by Django 5.0.1 on 2024-12-18 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0026_vendorprofile_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('447faff9-7b5f-4af8-a308-43fac632694f')),
        ),
    ]
