# Generated by Django 5.0.1 on 2024-12-19 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0027_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('36583132-d2d4-4a45-8c6e-94d252e8f4fb')),
        ),
    ]
