# Generated by Django 5.0.1 on 2024-12-19 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0028_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('a1005936-dd94-49d7-ae9c-39d8656735bd')),
        ),
    ]
