# Generated by Django 5.0.1 on 2024-12-20 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0030_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='percentage_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('8e3a931e-c44f-4959-adc5-5ff88353ac7a')),
        ),
    ]
