# Generated by Django 5.0.1 on 2024-12-20 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0031_product_discounted_price_product_percentage_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firebase_token',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('a2c44fbe-6c0d-4567-a7ea-196832db5174')),
        ),
    ]
