# Generated by Django 5.0.1 on 2024-12-22 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0033_orderdetail_vendor_id_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image4',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('aad4f32f-f844-4c66-a13a-6abcd79dcf6a')),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restapi.product')),
            ],
        ),
    ]
