# Generated by Django 5.0.1 on 2024-12-24 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0034_remove_product_product_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('b490e3ae-6911-4f9e-a0d8-7f644997911b')),
        ),
    ]
