# Generated by Django 5.0.1 on 2024-12-25 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0035_remove_vendorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_image',
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('31abc971-bfdc-4781-8f8b-56b02e05b613')),
        ),
    ]
