# Generated by Django 5.0.1 on 2024-12-25 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0036_remove_orderdetail_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('0db874a9-98ec-42b5-88e5-3b092ec45368')),
        ),
    ]
