# Generated by Django 5.0.1 on 2024-12-28 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0039_alter_vendorprofile_vendor_id_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('acfc4d83-3c5b-4d89-8d20-ba0cc9d8fdfb')),
        ),
    ]
