# Generated by Django 5.0.1 on 2024-12-30 21:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0042_rename_product_image_product_vendor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='product_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('e9806b2d-173c-4893-a27c-6818c414f52e')),
        ),
    ]
