# Generated by Django 5.0.1 on 2024-12-30 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0043_orderdetail_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='vendor_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('c3168ca7-0105-42a5-aff3-f300451f9431')),
        ),
    ]
