# Generated by Django 5.0.1 on 2025-01-12 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0046_alter_vendorprofile_vendor_id_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('247450d0-8707-4035-b29e-9e714051aca6')),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
