# Generated by Django 5.0.1 on 2025-01-21 21:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0048_pending_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='account_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pending',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='reverse_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('f5ddb080-14f5-4c9f-982f-db9f27905fbc')),
        ),
    ]
