# Generated by Django 5.0.1 on 2025-01-22 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0049_pending_account_number_pending_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='buyer_id',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('9c4b5d49-ee01-4a6a-a360-e43353cc867a')),
        ),
    ]
