# Generated by Django 5.0.1 on 2025-01-22 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0050_buyerprofile_buyer_id_vendorprofile_vendor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('12b09573-c6d1-4208-bb91-23f01f1fe34f')),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='', max_length=20)),
                ('transaction_type', models.CharField(choices=[('Order', 'Order'), ('Reverse payment', 'Reverse payment'), ('Transfer', 'Transfer')], default='', max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('recipient', models.CharField(max_length=20)),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_quantity', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
