# Generated by Django 5.0.1 on 2025-01-22 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0051_alter_vendorprofile_vendor_id_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='sender',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('57db0fd2-8dd7-43a1-8fd4-7be104301699')),
        ),
    ]
