# Generated by Django 5.0.1 on 2025-01-23 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0053_alter_transactionhistory_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('adb3e0e1-9bb0-43ec-8227-288b6a193b8e')),
        ),
    ]
