# Generated by Django 5.0.1 on 2025-01-23 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0054_transactionpercentage_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpercentage',
            name='name',
            field=models.CharField(default='Transaction percentage', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('6845ba2b-df8c-4324-8e2b-27352d81f555')),
        ),
    ]
