# Generated by Django 5.0.1 on 2025-01-24 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0055_transactionpercentage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('18751f11-3066-4b0b-8739-b3487dc6d3e7')),
        ),
    ]
