# Generated by Django 5.0.1 on 2025-01-24 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0056_pending_product_id_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('ef50032e-5ace-4726-a8f3-fde08b1be6e9')),
        ),
    ]
