# Generated by Django 5.0.1 on 2025-01-27 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0058_remove_orderdetail_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('f6b12f9a-94af-49be-8de9-337e71d59618')),
        ),
    ]
