# Generated by Django 5.0.1 on 2025-01-27 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0059_vendorprofile_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('a63b592d-ab89-4bf8-ae41-d7a8b2d7a3df')),
        ),
    ]
