# Generated by Django 5.0.1 on 2025-01-27 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0060_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('4a80bc53-87cb-47b0-94e5-573eefadabbe')),
        ),
    ]
