# Generated by Django 5.0.1 on 2025-02-19 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0062_customuser_transaction_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='transaction_pin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('318e33d4-7e6f-4bab-9c10-578c7d958c0b')),
        ),
    ]
