# Generated by Django 5.0.1 on 2025-02-20 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0063_alter_customuser_transaction_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.CharField(choices=[('Alex Ekwueme Federal University, Ndufu Alike Ikwo', 'Alex Ekwueme Federal University Ndufu Alike Ikwo'), ('Ebonyi State University, Abakaliki', 'Ebonyi State University, Abakaliki')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('24203ea0-fb96-469e-850b-aa2812764d1d')),
        ),
    ]
