# Generated by Django 5.0.1 on 2025-02-24 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0064_customuser_school_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='school',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('bf231778-3582-4a0e-bc4a-8443104d0739')),
        ),
    ]
