# Generated by Django 5.0.1 on 2025-03-04 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0067_alter_vendorprofile_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('d07305b7-8a09-4ccf-b04c-af35c50a9062')),
        ),
    ]
