# Generated by Django 5.0.1 on 2025-03-05 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0069_alter_vendorprofile_vendor_id_emailotptokengenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Subscription funds', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('reset', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='transactionpercentage',
            name='reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('0e0bdeab-98de-4c0d-8395-bafed77cf343')),
        ),
    ]
