# Generated by Django 5.0.1 on 2025-03-05 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0070_subscriptionfunds_transactionpercentage_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('16a207da-79c7-47d9-bfa7-1e9cdb3da226')),
        ),
    ]
