# Generated by Django 5.0.1 on 2025-03-10 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0071_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('Order', 'Order'), ('Reverse payment', 'Reverse payment'), ('Transfer', 'Transfer'), ('Deposit', 'Deposit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('ee839e48-9678-4b74-9d80-c9fcf43821cd')),
        ),
    ]
