# Generated by Django 5.0.1 on 2025-03-12 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0072_alter_transactionhistory_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotptokengenerator',
            name='otp_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otptokengenerator',
            name='otp_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionotptokengenerator',
            name='otp_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('9452ac91-01e0-46fc-b355-19e7f8434c64')),
        ),
    ]
