# Generated by Django 5.0.1 on 2025-04-21 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0073_alter_emailotptokengenerator_otp_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pending',
            name='otp_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionfunds',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionpercentage',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('7a2b52ee-7d6d-4faa-b86f-76d156ed67cd')),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
