# Generated by Django 5.0.1 on 2025-04-21 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0075_orderdetail_product_id_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='product_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productreview',
            name='vendor_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('c30a1b81-9dbf-4020-b62b-94cc413bb815')),
        ),
    ]
