# Generated by Django 5.0.1 on 2025-04-22 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0077_productreview_edited_at_productreview_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('5dde37f4-c330-4e7f-9fe0-dd21f564981b')),
        ),
    ]
