# Generated by Django 5.0.1 on 2025-04-26 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0078_productreview_order_pk_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_user_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('81dd9f6f-4546-4f55-846f-b825088ab522')),
        ),
    ]
