# Generated by Django 5.0.1 on 2025-04-27 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0081_alter_vendorprofile_vendor_id_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
