# Generated by Django 5.0.1 on 2025-04-27 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0083_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='usermessage',
            name='group_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('717a10df-79bc-4f96-8940-54b0eca5a9ee')),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restapi.groupname'),
        ),
    ]
