# Generated by Django 5.0.1 on 2025-04-27 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0084_groupname_usermessage_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('cebc5482-c844-460c-9750-6c191155a442')),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('f339eca5-57d1-46af-9e5d-1e6572a82148')),
        ),
    ]
