# Generated by Django 5.0.1 on 2025-04-27 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0085_vendorprofile_vendor_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('0e5d66e4-6a7a-48d5-92bd-26e62380e746')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('23a64ac5-618c-46c8-aced-b01bb136ec68')),
        ),
    ]
