# Generated by Django 5.0.1 on 2025-04-28 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0086_alter_usermessage_user_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='user_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupname',
            name='user_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_upload'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('588ad569-f001-4ccd-9a5d-8adf9203cf7f')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('dfd465fb-b196-410e-9e7f-b41e49a6fd55')),
        ),
    ]
