# Generated by Django 5.0.1 on 2025-04-28 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0087_groupname_user_1_groupname_user_2_usermessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('voice', 'Voice message')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('5b0f2601-b579-4422-80b8-cd1ac6404130')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('23defcfe-d540-47d1-8086-7bf30fd0ac4d')),
        ),
    ]
