# Generated by Django 5.0.1 on 2025-05-10 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0088_alter_usermessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='user_token',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('afa23392-f5c7-4772-a2f9-9e9b89ef3bca')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('0981bc5f-6b88-465f-a43d-195f86161d7f')),
        ),
    ]
