# Generated by Django 5.0.1 on 2025-05-10 23:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0089_usermessage_user_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('32856da4-4cce-44ee-bc37-2c9491766b24')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('a2cc83b6-e750-44dd-9d87-64269775a456')),
        ),
    ]
