# Generated by Django 5.0.1 on 2025-05-11 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0090_alter_usermessage_user_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('bd6cfece-fab9-4f28-8808-acc14783768b')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('556bdc4e-c426-4511-975e-ccc7b0f5f41e')),
        ),
    ]
