# Generated by Django 5.0.1 on 2025-05-11 17:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0091_alter_usermessage_user_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('5fc83871-f1e2-4b84-971d-7ed85b658d64')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('b72e5f82-50f9-4648-bac4-17e2b53f54c8')),
        ),
    ]
