# Generated by Django 5.0.1 on 2025-05-13 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0092_groupname_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('fashion', 'fashion'), ('footwears', 'footwears'), ('phones and accessories', 'phones and accessories'), ('electronics', 'electronics'), ('beauty', 'beauty'), ('household', 'household'), ('groceries', 'groceries'), ('food', 'food'), ('service listing', 'service listing')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('cde2582e-b10f-482a-8b49-f76c03847602')),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_chat_id',
            field=models.UUIDField(default=uuid.UUID('cda4b738-cedd-4533-8280-15237622fc3b')),
        ),
    ]
